Ecomm_Project/config/routes.rb
Rails.application.routes.draw do
  resources :orders

  resources :provinces

  resources :customers

  resources :pages

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root to: 'finder#index'
  get 'product/:id' => 'finder#show', constraints: {id: /\d+/}, as: 'product'
  get 'page/:id' => 'pages#show', as: 'page2'
  get 'category/:id' => 'categories#show', as: 'category'
  get 'search_results' => 'finder#search_results', as: 'search_results'
  post 'favourite_product/:id' => 'finder#save_favourite_product', as: 'save_fav_prod'
  get 'category_search_results' => 'finder#category_search_results', as: 'category_search_results'
  get 'purchase/:id' => 'finder#save_product', as: 'purchase'
  get 'new_order' => 'customers#new', as: 'customer_info_screen'
  get 'add_new_customer' => 'customers#add_new_customer'
end

Ecomm_Project/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

Ecomm_Project/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  validates :category_name, presence: true
  def name
    self.category_name
  end
end

Ecomm_Project/app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :province
  belongs_to :order
  validates :first_name, :last_name, :address, :postalcode, presence: true
end

Ecomm_Project/app/models/order.rb
class Order < ActiveRecord::Base
  has_one :customer
  has_many :products
end

Ecomm_Project/app/models/page.rb
class Page < ActiveRecord::Base
end

Ecomm_Project/app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :orders
  validates :product_name, presence:true
  validates :price, presence: true
  validates :quantity, numericality: true
end

Ecomm_Project/app/models/province.rb
class Province < ActiveRecord::Base
  has_many :customers
  validates :name, :tax, presence: true
end

Ecomm_Project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Ecomm_Project/app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
  before_action :load_fav_prod, except: :save_favourite_product
  
  def show
    categoryId = params[:id]
    @products = Product.where(category_id: categoryId).order("product_name").page(params[:page]).per(6)
    @pages = Page.all
    @categories = Category.all
  end
  
  def save_favourite_product
    session[:fav_prod_id] = params[:id]
    redirect_to :back
  end
  
  private 
  def load_fav_prod
    if session[:fav_prod_id]
      @fav_prod = Product.find(session[:fav_prod_id])
    else
      @fav_prod = false
    end 
  end
end

Ecomm_Project/app/controllers/customers_controller.rb
class CustomersController < InheritedResources::Base
  def new
    @pages = Page.all
    @categories = Category.all
    @provinces = Province.all
  end
  
  def add_new_customer
    new_customer = Customer.new(params[:first_name], params[:last_name], params[:address], params[:city], params[:postalcode], params[:province_id])  
  end
  
  private

    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :address, :city, :postalcode)
    end
end

Ecomm_Project/app/controllers/finder_controller.rb
class FinderController < ApplicationController
  
  before_action :load_fav_prod, except: :save_favourite_product
  def index
    @products = Product.order("product_name").page(params[:page]).per(6)
    @pages = Page.all
    @categories = Category.all
    
  end
  def show
    @pages = Page.all
    @categories = Category.all
    @product = Product.find(params[:id])
  end
  
  def search_results
    wildcard_keywords = '%' + params[:search_keywords] + '%'
    @products = Product.where("product_name LIKE ?", wildcard_keywords).order("product_name").page(params[:page]).per(6)
    @pages = Page.all
    @categories = Category.all
  end
  
  def category_search_results
    @categories = Category.all
    @pages = Page.all
    wildcard_keywords = '%' + params[:search_keywords] + '%'
    @products = Product.where("category_id = ? AND product_name LIKE ?", params[:my_option], wildcard_keywords).order("product_name").page(params[:page]).per(6)
  end
  
  def save_product
    session[:product_to_purchase] = params[:id]
    redirect_to customer_info_screen_path
  end
  
  def save_favourite_product
    session[:fav_prod_id] = params[:id]
    redirect_to :back
  end
  
  private 
  def load_fav_prod
    if session[:fav_prod_id]
      @fav_prod = Product.find(session[:fav_prod_id])
    else
      @fav_prod = false
    end 
  end
end

Ecomm_Project/app/controllers/orders_controller.rb
class OrdersController < InheritedResources::Base

  private

    def order_params
      params.require(:order).permit()
    end
end

Ecomm_Project/app/controllers/pages_controller.rb
class PagesController < InheritedResources::Base
  before_action :load_fav_prod, except: :save_favourite_product
  
  def show
    @pages = Page.all
    @page = Page.find(params[:id])
    @categories = Category.all
  end

  private  
    def page_params
      params.require(:page).permit(:content)
    end
    
  private 
  def load_fav_prod
    if session[:fav_prod_id]
      @fav_prod = Product.find(session[:fav_prod_id])
    else
      @fav_prod = false
    end 
  end
end

Ecomm_Project/app/controllers/provinces_controller.rb
class ProvincesController < InheritedResources::Base

  private

    def province_params
      params.require(:province).permit(:name)
    end
end

Ecomm_Project/app/helpers/application_helper.rb
module ApplicationHelper
end

Ecomm_Project/app/helpers/customers_helper.rb
module CustomersHelper
end

Ecomm_Project/app/helpers/finder_helper.rb
module FinderHelper
end

Ecomm_Project/app/helpers/orders_helper.rb
module OrdersHelper
end

Ecomm_Project/app/helpers/pages_helper.rb
module PagesHelper
end

Ecomm_Project/app/helpers/provinces_helper.rb
module ProvincesHelper
end

Ecomm_Project/app/views/categories/show.html.erb
<%= render @products %>
<%= paginate @products %>

Ecomm_Project/app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :postalcode %><br>
    <%= f.text_field :postalcode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Ecomm_Project/app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

Ecomm_Project/app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Address</th>
      <th>City</th>
      <th>Postalcode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.address %></td>
        <td><%= customer.city %></td>
        <td><%= customer.postalcode %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

Ecomm_Project/app/views/customers/new.html.erb
<div id="CMS">
  <h1>Customer info</h1>
  
  <%= form_tag add_new_customer_path, method: :get do %>
    <div class="field">
      <p>First name:</p>
      <%= text_field_tag  :first_name %>
    </div>
    <div class="field">
      <p>Last name:</p>
      <%= text_field_tag  :last_name %>
    </div>
    <div class="field">
      <p>Address:</p>
      <%= text_field_tag  :address %>
    </div>
    <div class="field">
      <p>City:</p>
      <%= text_field_tag  :city %>
    </div>
    <div>
      <p>Province:</p>
      <%= select_tag :province_id, options_from_collection_for_select(@provinces, 'id', 'name') %>
    </div>
    <div class="field">
      <p>Postal Code</p>
      <%= text_field_tag  :postalcode %>
    </div>
    <div class="actions">
      <%= submit_tag "Submit Order" %>
    </div>
  <% end %>
  
  <%= link_to 'Cancel', root_path %>
</div>

Ecomm_Project/app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @customer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @customer.last_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @customer.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @customer.city %>
</p>

<p>
  <strong>Postalcode:</strong>
  <%= @customer.postalcode %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

Ecomm_Project/app/views/finder/category_search_results.html.erb
<h2>Search Results for '<%= params[:search_keywords] %>': </h2>
<% if @products.size.zero? %>
  <p>No products found.</p>
<% else %>
  <p><%= pluralize(@products.size, 'Product') %> found.</p>
  <%= render @products %>
  <%= paginate @products %>
<% end %>
  

Ecomm_Project/app/views/finder/index.html.erb
<%= render @products %>
<%= paginate @products %>

Ecomm_Project/app/views/finder/search_results.html.erb
<h2>Search Results for '<%= params[:search_keywords] %>': </h2>
<% if @products.size.zero? %>
  <p>No products found.</p>
<% else %>
  <p><%= pluralize(@products.size, 'Product') %> found.</p>
  <%= render @products %>
  <%= paginate @products %>
<% end %>
  

Ecomm_Project/app/views/finder/show.html.erb
<div id="singleProduct">
  <h2><%= @product.product_name %></h2>
  <%= image_tag(@product.image) %> <%= image_tag(@product.image.insert(-5, '2')) %>
  <p>Price: <%= @product.price %></p>
  <p>Category: <br />
  <% if @product.category.present? %>
    <%= @product.category.name %>
  <% end %>
  </p>
  <p id="favourite">
    <%= link_to 'Set as favourite product', save_fav_prod_path(@product), method: :post %>
  </p>
  <%= form_tag purchase_path(@product.id), method: :get do %>
    <%= submit_tag 'Purchase' %>
  <% end %>
</div>

Ecomm_Project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Winnipeg Gundam Guy</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/nav' %>
    <%= render 'shared/sideNav' %>
    <div id="mainContainer">
      <%= yield %>
    </div>
  </body>
</html>

Ecomm_Project/app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Ecomm_Project/app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

Ecomm_Project/app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

Ecomm_Project/app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

Ecomm_Project/app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

Ecomm_Project/app/views/pages/show.html.erb
<div id="CMS">
  <h1><%= @page.name %></h1>
  <p><%=simple_format h @page.content %></p>
</div>

Ecomm_Project/app/views/products/_product.html.erb
<div class="product">
  <h2><%= link_to product.product_name, product %></h2>
  <p><%= image_tag(product.image) %></p>
  <p>Price: <%= product.price %></p>
  <p>Category: <br />
  <% if product.category.present? %>
    <%= product.category.name %>
  <% end %>
  </p>
  <p id="favourite">
    <%= link_to 'Set as favourite product', save_fav_prod_path(product), method: :post %>
  </p>
  <%= form_tag purchase_path(product.id), method: :get do %>
    <%= submit_tag 'Purchase' %>
  <% end %>
</div>

Ecomm_Project/app/views/provinces/_form.html.erb
<%= form_for(@province) do |f| %>
  <% if @province.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@province.errors.count, "error") %> prohibited this province from being saved:</h2>

      <ul>
      <% @province.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Ecomm_Project/app/views/provinces/edit.html.erb
<h1>Editing province</h1>

<%= render 'form' %>

<%= link_to 'Show', @province %> |
<%= link_to 'Back', provinces_path %>

Ecomm_Project/app/views/provinces/index.html.erb
<h1>Listing provinces</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @provinces.each do |province| %>
      <tr>
        <td><%= province.name %></td>
        <td><%= link_to 'Show', province %></td>
        <td><%= link_to 'Edit', edit_province_path(province) %></td>
        <td><%= link_to 'Destroy', province, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Province', new_province_path %>

Ecomm_Project/app/views/provinces/new.html.erb
<h1>New province</h1>

<%= render 'form' %>

<%= link_to 'Back', provinces_path %>

Ecomm_Project/app/views/provinces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @province.name %>
</p>

<%= link_to 'Edit', edit_province_path(@province) %> |
<%= link_to 'Back', provinces_path %>

Ecomm_Project/app/views/shared/_header.html.erb
<header>
  <h1>Winnipeg Gundam Guy</h1>
</header>

Ecomm_Project/app/views/shared/_nav.html.erb
<nav id="mainNav">
  <div id="leftNav">
    <%= link_to 'Home', root_path %>
    <% @pages.each do |page| %>
      <%=  link_to page.name, page  %>
    <% end %>
  </div>
  <div id="rightNav">
    <p>Keyword search by category:</p>
    <%= form_tag category_search_results_path, method: :get do %>
     <%= select_tag :my_option, options_from_collection_for_select(@categories, 'id', 'name') %>
     <%= text_field_tag :search_keywords %>
     <%= submit_tag "Search" %>
    <% end %>
  </div>
  <div class="clear"></div>
</nav>

Ecomm_Project/app/views/shared/_sideNav.html.erb
<nav id="sideNav">
  <h3>Search By Keyword</h3>
  <%= form_tag search_results_path, method: :get do %>
    <%= text_field_tag :search_keywords %>
    <%= submit_tag 'Search' %>
  <% end %>
  <br />
  <h3>Shop By Category:</h3>
  <%= link_to "All Products", root_path %>
  <br />
  <% @categories.each do |category| %>
    <%= link_to category.name, category %>
    <br />
  <% end %>
  <br />
  <h3>Favourite Product</h3>
  <% if @fav_prod %>
    <div id="favProd">
      <%= render @fav_prod %>
    </div>
    <% else %>
      <p>None Saved.</p>
  <% end %>
</nav>